### ISSUE TITLE
Personal Demon Mode

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#20]
### Summary
The personal demon has to be nice and animated

### Technical Spec
Simply drawing to the OLED

### Think About
Health is easy to see. Fat/Thin is easy to see, but it overlaps with sick. Discipline and happiness are impossible to see. Should that be more visible, or should they be hidden parameters?

### TODO
- [x] Save/load current demon state to NVM
- [x] Add 'Records' option to menu which lists prior demons and their ages
- [X] Change visible demon state (fat, sick, etc.) _after_ the action happens. Ex. fat after eating, healthy after being cured.
- [x] Shorten text, optimize text plotting
- [x] Switch to `menu2d` system
- [x] Disable inputs during animations
- [x] Spawn a new demon after death
- [x] Health bar
- [x]  Multiple randomized demons
- [x] LEDs based on happiness / hunger / discipline / sickness
### UI
**Actions**
- [x] Playing
- [x] Refusing to play
- [X] Eating
- [x] Refusing to eat
- [X] Overeating
- [x] Scooping Poop
- [X] Being Scolded
- [ ] Being Scolded when sick
- [X] Coming out of a portal
- [X] Getting Medicine, being cured
- [ ] Getting Medicine, not being cured

**Events**
- [ ] Getting sick
- [X] Pooping
- [ ] Losing discipline
- [X] Dying

### How to Test

Make temporary menu options that trigger the individual animations
