### ISSUE TITLE
Raycaster Mode

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#29]
**Summary**
Turn the raycaster into a real game. The player should be able to walk around and shoot/zap enemies. Enemies should also walk around and shoot/zap back. Player and enemy health will be tracked. Player may have infinite ammo, or ammo pickups, unsure.

**TODOs**
- [x] Cast walls
- [x] Texture Walls
- [x] Cast Sprites
- [x] Draw HUD sprites (gun? health/ammo indicator?)
- [x] Animate enemy sprites (walking, firing, being shot)
- [x] ~~Health and ammo pickups?~~
- [x] Make basic enemy AI (walking around, shooting player)
- [x] Add top level menu
- [x] Add difficulty options
- [x] Add high scores (time to clear?)
- [x] LED Support (getting shot, shooting something, passive radar)

**Comment by AEFeinstein** [comment]
Doom monster behavior. Seems simple and good enough to use.
> Monsters generally try to close in on their target via the shortest possible route. If the direct route to the target is blocked by a wall or a solid thing that the monster walks into, it randomly picks another direction to move in for a short while (to find another route to its target) until it reverts to heading straight toward its target again.
> 
> A monster does not need to have a line of sight to follow its target, and will attempt to close in on its position within the level.
> 
> If a monster with no melee attack reaches its target and "bumps" into it, it will move away from it for a while in a similar fashion it does when hitting any other obstacle.
> 
> If a monster has no target, it is in the dormant state and will not move.

**Comment by AEFeinstein** [comment]
Sprite movement directly to the player is a bit much, maybe only do it on X or Y axis?

**Comment by AEFeinstein** [comment]
Feedback from @jt-moriarty 

- [x] Enemy corpses block player shot, but don't block enemy shots (need to make symmetric)
- [ ] ~~Damage animation is a bit prolonged, shorten that up~~
- [x] Add tension at low health (pulse LEDs?)
- [x] Add more feedback when taking damage (flash heart in addition to red LEDs)
- [ ] ~~Hard to place self visually, wall textures were a hint. Not sure if there's anything to be done here~~

**Comment by AEFeinstein** [comment]
@jt-moriarty toying with the raycaster, I realize that one of the reasons I made the 'hurt' animation a little slower was to have a visual cooldown on when the sprite could get shot. This incentivizes players to not focus-fire on harder difficulties. With a quicker animation, its a bit too easy to shoot twice real fast. Knowing that, what are your thoughts on the animation speed?

**Comment by Brycey92** [comment]
Perhaps the walls need some more-regular textures like vertical/horizontal gridlines, diagonals, repeated squares or circles, etc. Kinda like VR chaperone bounds.

**Comment by AEFeinstein** [comment]
My principles for the textures were

* 48px x 48px
* Avoid continuous vertical lines. That's because corners between walls are always drawn as vertical lines, and if those are the _only_ vertical lines, they're easier to distinguish and help you place yourself in the map.
* Avoid a black horizontal stripe in the middle of the texture. This is because if you run right up to the wall, it wouldn't draw anything. This was actually a bigger problem before the HUD was drawn, now it doesn't matter as much
* Make sure each detail was at least 2px wide so that it would scale relatively well.
* Tile horizontally (and vertically, just for kicks)
* Have three visually distinctive textures so you could tell when you could distinguish what room you're in
* Have a fourth texture specifically for objects within rooms, not attached to walls.

Here's what I came out with:

Walls:
![txbrick](https://user-images.githubusercontent.com/231180/97781102-8c9eea00-1b5f-11eb-8ed2-75536c706bdc.png)
![txstripe](https://user-images.githubusercontent.com/231180/97781105-8d378080-1b5f-11eb-99bd-64d177e4048e.png)
![txsinw](https://user-images.githubusercontent.com/231180/97781103-8d378080-1b5f-11eb-8c69-815935bd144b.png)
Room objects:
![txstone](https://user-images.githubusercontent.com/231180/97781104-8d378080-1b5f-11eb-86ac-5fcffbabfa8a.png)

With all that in mind, would you like to draw some more-regular textures?

**Comment by Brycey92** [comment]
Perhaps if I have enough free time after the final tweaks to tunernome, but don't count on me getting to it before the feature freeze. Though I guess this counts as fixes so we're able to do it after the freeze?

**Comment by AEFeinstein** [comment]
Yeah. Something like "add more textures, redo whole map" is something I'd rather not do, but "replace texture" is pretty trivial to do.

**Comment by AEFeinstein** [comment]
@jt-moriarty added a red LED pulse at quarter health, on screen icon blinks when you lose health or defeated an enemy
