### ISSUE TITLE
Flappy Mode

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#30]
**Summary**
What is the feature all about?

**TODO**
- [ ] Use microphone for 'clap' mode (flappy bird physics)
- [ ] Use microphone for 'tone' mode (chopper physics). Should this track changes in tone (up/down) or map to tone absolutely? If mapped absolutely to note, is wraparound acceptable?
- [ ] Tweak difficulties (don't shrink the tunnel? change bar frequency/size instead?)
- [ ] Display score after the player crashes
- [ ] Save the high score to NVM
- [ ] Add high score viewing option to to top level menu
- [ ] Come up with a better name and sprite for the player

**Comment by AEFeinstein** [comment]
Eh, not gonna do this one
