### ISSUE TITLE
Stomp Mode

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#31]
**Summary**
It's a game about dancing. Mostly done at this point

**TODO**
- [x] Have other people test difficulties
- [x] Save high scores (convert perfect/good/miss to some number or letter rank?)
- [x] Add high score entry to menu and display high scores
