### ISSUE TITLE
Galaga Mode

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#32]
**Summary**
Leaving up to @jt-moriarty 

**TODO**
- [x] ???

**Comment by AEFeinstein** [comment]
See https://github.com/jt-moriarty/Super-2021-Swadge-FW-Sandbox

**Comment by AEFeinstein** [comment]
@Dacvak's feedback based on the 12/22 build (which isn't finished, I know)
- [x] Have powerups drift leftward over time
- [x] Add a difficulty option
- [x] Add some incentive to collect powerups later in the game. Maybe have the weapon degrade over time? Maybe require more powerups per weapon upgrade? 10x powerup does something special, auto-bomb?
- [x] More enemies, more bullet hell in later levels!
- [x] Dac offered to do sprite work, but I know you have a person already
- [x] Loved the reflect mechanic
- [x] Have three lives/hearts?
- [x] Don't show waves/enemies on menu screen (bug)

**Comment by AEFeinstein** [comment]
Do a little cleanup from https://github.com/AEFeinstein/Super-2021-Swadge-FW-Sandbox/pull/120, then close this out
