### ISSUE TITLE
Colorchord Mode

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#33]
**Expected Behavior**
It's Colorchord!

**TODO**
- [x] Write a GUI to adjust mic sensitivity (1-10 or whatever)
- [x] Write a GUI to adjust output mode (all one color, rainbow)
- [x] ~~Write a GUI to enable or disable animation~~ WON'T DO
- [x] ~~Write some animation (or multiple) based on frequency~~ WON'T DO
- [x] ~~Animation acts as a 'screensaver' when not using the GUI to adjust parameters~~ WON'T DO
- [x] Some button should exit (left?)

**Comment by Brycey92** [comment]
Should we re-add the functionality to change LED brightness?

**Comment by AEFeinstein** [comment]
There never was an option to change LED brightness, but changing the mic sensitivity does virtually the same thing.

**Comment by Brycey92** [comment]
I feel like every mode on the 2019 swadge had 2 or 3 brightnesses, but maybe I'm just misremembering.

Technically, changing brightness changes *max* brightness, which can't be accomplished by changing mic sensitivity.

**Comment by AEFeinstein** [comment]
I'm reasonably confident that the two buttons for Reflector Colorchord were
1. Switch single color / multi-color output
1. Adjust mic sensitivity (_virtually_ changes brightness, I know it doesn't actually change the max.)

**Comment by Brycey92** [comment]
Fair enough.

Is the OLED supposed to keep flashing to black during colorchord, or is something broken?

**Comment by AEFeinstein** [comment]
Sounds like something broken. For #42 I added an OLED reset any time there's an I2C error detected, which'd look like a black flash. Could be related?

**Comment by Brycey92** [comment]
Ah, it does happen more often if i move the swadge in its connector or touch the pins on the bottom of the programmer. Is there any way to solve the pins-touching issue without the black flash?

**Comment by AEFeinstein** [comment]
I didn't see any SPI instructions to completely reset the OLED without the temporary-off. I did try resending all of the init commands beside the reset, and that did not resolve the corruption.

**Comment by Brycey92** [comment]
For those not following along on slack, the screen-blanking issue has been resolved.

**Comment by AEFeinstein** [comment]
UI done in #76. A few notes:
- The only animation is going to be the spectrogram, unless someone thinks of and implements something else cool
- The animation will always be drawn. This is easier than making it toggleable
- The animation is drawn at the same time as the UI, so no need to flip between the two
